// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS.Models;

public partial class LeaveRequest
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string LeaveType { get; set; }

    public string Status { get; set; }

    public virtual Employee Employee { get; set; }
}