// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS.Models;

public partial class Payroll
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public DateOnly PayrollDate { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? Bonus { get; set; }

    public decimal? Deductions { get; set; }

    public virtual Employee Employee { get; set; }
}